//! App-side part-mesh catalog + loader (WI 653): map a mechanical-kit part to its shipped glb and
//! spawn it at a mount, oriented/scaled per the catalog frame (+Y up, +Z forward, +X axle; reference
//! cell 0.5 m). The catalog table also feeds the gallery inspector. App-side only — the headless
//! crate has no notion of meshes.
//!
//! glb assets live under `assets/models/parts/<name>.glb`, generated by the asset-harness
//! `mechanical-kit` track (parametric Blender geometry + AI PBR surfaces). A part identity with no
//! shipped glb falls back to a caller-supplied placeholder via [`part_glb_path`] returning `None`.

use bevy::gltf::GltfAssetLabel;
use bevy::prelude::*;
use sounding_sim::voxel::{device_mass, DeviceKind, PartKind};

/// The reference cell the parts were authored at (manifest `reference_cell`); a part is scaled by
/// `cell_size / REFERENCE_CELL` so it matches the build's cell size.
pub const REFERENCE_CELL: f64 = 0.5;

/// Catalog grouping for the gallery layout.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum PartCategory {
    Drivetrain,
    Power,
    Cockpit,
    Structure,
    Comms,
    Rocket,
    Fitting,
}

impl PartCategory {
    pub fn label(self) -> &'static str {
        match self {
            PartCategory::Drivetrain => "Drivetrain",
            PartCategory::Power => "Power",
            PartCategory::Cockpit => "Cockpit",
            PartCategory::Structure => "Structure",
            PartCategory::Comms => "Comms",
            PartCategory::Rocket => "Rocket",
            PartCategory::Fitting => "Fittings",
        }
    }

    /// Layout/row order in the gallery.
    pub const ORDER: [PartCategory; 7] = [
        PartCategory::Drivetrain,
        PartCategory::Power,
        PartCategory::Cockpit,
        PartCategory::Structure,
        PartCategory::Comms,
        PartCategory::Rocket,
        PartCategory::Fitting,
    ];
}

/// A catalog entry: the glb basename plus the metadata the gallery inspector shows. `device` ties a
/// part to a `DeviceKind` so device-backed parts (motor/battery/tank/…) can report a mass.
pub struct CatalogPart {
    pub name: &'static str,
    pub category: PartCategory,
    pub material_set: &'static str,
    pub orientation: &'static str,
    pub verts: u32,
    pub device: Option<DeviceKind>,
}

/// The shipped part catalog (mirrors `mechanical-kit/parts/manifest.json`).
pub const CATALOG: &[CatalogPart] = &[
    // Drivetrain
    CatalogPart { name: "tire", category: PartCategory::Drivetrain, material_set: "rubber", orientation: "+X axle; rolls +Z", verts: 192, device: None },
    CatalogPart { name: "rim", category: PartCategory::Drivetrain, material_set: "metal_panel", orientation: "+X axle", verts: 256, device: None },
    CatalogPart { name: "suspension", category: PartCategory::Drivetrain, material_set: "metal_panel", orientation: "strut +Y to chassis", verts: 152, device: None },
    CatalogPart { name: "motor", category: PartCategory::Drivetrain, material_set: "motor_casing", orientation: "+X axle; shaft +X", verts: 792, device: Some(DeviceKind::Engine) },
    // Power
    CatalogPart { name: "battery", category: PartCategory::Power, material_set: "battery", orientation: "upright; terminals +Y", verts: 304, device: Some(DeviceKind::Battery) },
    CatalogPart { name: "solar_panel", category: PartCategory::Power, material_set: "solar_cells", orientation: "panel in XZ, normal +Y", verts: 80, device: None },
    CatalogPart { name: "solar_panel_2x1", category: PartCategory::Power, material_set: "solar_cells_2x1", orientation: "panel in XZ, normal +Y", verts: 80, device: None },
    // Cockpit
    CatalogPart { name: "seat", category: PartCategory::Cockpit, material_set: "seat_fabric", orientation: "faces +Z, up +Y", verts: 48, device: Some(DeviceKind::Command) },
    CatalogPart { name: "seat_leather", category: PartCategory::Cockpit, material_set: "leather_light", orientation: "faces +Z, up +Y", verts: 48, device: Some(DeviceKind::Command) },
    CatalogPart { name: "steering_wheel", category: PartCategory::Cockpit, material_set: "leather_light", orientation: "rim in XY, faces +Z", verts: 664, device: None },
    CatalogPart { name: "tablet", category: PartCategory::Cockpit, material_set: "screen_ui", orientation: "screen faces +Z", verts: 56, device: Some(DeviceKind::Computer) },
    // Structure
    CatalogPart { name: "bumper", category: PartCategory::Structure, material_set: "metal_panel", orientation: "long axis +X, front +Z", verts: 56, device: None },
    // Comms
    CatalogPart { name: "antenna", category: PartCategory::Comms, material_set: "metal_panel", orientation: "mast along +Y", verts: 610, device: None },
    CatalogPart { name: "dish_small", category: PartCategory::Comms, material_set: "white_hull", orientation: "opens +Z", verts: 610, device: None },
    CatalogPart { name: "dish_large", category: PartCategory::Comms, material_set: "white_hull", orientation: "opens +Z", verts: 610, device: None },
    // Rocket
    CatalogPart { name: "fuel_tank", category: PartCategory::Rocket, material_set: "white_hull", orientation: "axis +Y; stacks up", verts: 128, device: Some(DeviceKind::Tank) },
    CatalogPart { name: "nose_cone", category: PartCategory::Rocket, material_set: "white_hull", orientation: "axis +Y; tip up", verts: 33, device: None },
    CatalogPart { name: "engine_bell", category: PartCategory::Rocket, material_set: "heat_metal", orientation: "axis +Y; exit -Y", verts: 64, device: Some(DeviceKind::Engine) },
    CatalogPart { name: "decoupler", category: PartCategory::Rocket, material_set: "metal_panel", orientation: "axis +Y; band", verts: 128, device: None },
    CatalogPart { name: "fin", category: PartCategory::Rocket, material_set: "metal_panel", orientation: "blade +X, up +Y", verts: 24, device: None },
    // Fittings
    CatalogPart { name: "hatch_round", category: PartCategory::Fitting, material_set: "metal_panel", orientation: "disc in XY, faces +Z", verts: 328, device: None },
    CatalogPart { name: "hatch_rect", category: PartCategory::Fitting, material_set: "metal_panel", orientation: "panel in XY, faces +Z", verts: 72, device: None },
];

/// The catalog entry for `name`, if any.
pub fn catalog_part(name: &str) -> Option<&'static CatalogPart> {
    CATALOG.iter().find(|p| p.name == name)
}

/// The asset path for a part glb, or `None` if the part is not in the catalog (the caller should then
/// fall back to a placeholder mesh rather than bind a missing path).
pub fn part_glb_path(name: &str) -> Option<String> {
    catalog_part(name).map(|p| format!("models/parts/{}.glb", p.name))
}

/// The glb basename a `DeviceKind` renders as (the retrofit mapping), or `None` (→ placeholder).
pub fn device_part_name(kind: DeviceKind) -> Option<&'static str> {
    Some(match kind {
        DeviceKind::Engine => "motor",
        DeviceKind::Tank => "fuel_tank",
        DeviceKind::Battery => "battery",
        DeviceKind::Computer => "tablet",
        DeviceKind::Command => "seat",
        DeviceKind::Rcs => return None,
    })
}

/// The glb basename a `PartKind` renders as (the workshop retrofit mapping). Every kind maps to a
/// catalogued part; the legacy monolithic `Wheel` shows as a `tire`.
pub fn part_kind_name(kind: PartKind) -> &'static str {
    match kind {
        PartKind::Wheel(_) => "tire",
        PartKind::Suspension(_) => "suspension",
        PartKind::Rim(_) => "rim",
        PartKind::Tire(_) => "tire",
        PartKind::Seat => "seat",
        PartKind::Antenna => "antenna",
        PartKind::SolarPanel => "solar_panel",
        PartKind::Bumper => "bumper",
    }
}

/// Spawn a part's glb `SceneRoot` at `translation`/`rotation`, scaled by `cell_size / REFERENCE_CELL`.
/// Returns the spawned root entity so the caller can attach markers. Assumes the part is in the
/// catalog (`part_glb_path` is `Some`); callers handle the placeholder case themselves.
pub fn spawn_part_mesh(
    commands: &mut Commands,
    asset_server: &AssetServer,
    name: &str,
    cell_size: f64,
    translation: Vec3,
    rotation: Quat,
) -> Entity {
    let path = part_glb_path(name).expect("spawn_part_mesh called for an uncatalogued part");
    let scene = asset_server.load(GltfAssetLabel::Scene(0).from_asset(path));
    let scale = (cell_size / REFERENCE_CELL) as f32;
    // The parts are authored +Y-up in Blender; the glTF exporter's Z-up→Y-up rotation lands their
    // "up" along -Z in glTF/Bevy space. Rotate +90° about X to bring it back to Bevy's +Y-up (and
    // forward to +Z, axle to +X) — the frame the manifest intends. Composed under the caller's
    // mount rotation so caller orientations still apply on top of the corrected part.
    let rotation = rotation * Quat::from_rotation_x(std::f32::consts::FRAC_PI_2);
    commands
        .spawn((
            SceneRoot(scene),
            Transform {
                translation,
                rotation,
                scale: Vec3::splat(scale),
            },
        ))
        .id()
}

/// The display mass (kg) of a device-backed part at `cell_size`, for the inspector.
pub fn part_device_mass(part: &CatalogPart, cell_size: f64) -> Option<f64> {
    part.device.map(|k| device_mass(k, cell_size))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_catalog_part_has_a_shipped_glb() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/models/parts");
        for p in CATALOG {
            let f = root.join(format!("{}.glb", p.name));
            assert!(f.exists(), "missing part glb: {}", f.display());
        }
    }

    #[test]
    fn every_device_kind_maps_to_a_catalogued_part_or_none() {
        for k in [
            DeviceKind::Command,
            DeviceKind::Engine,
            DeviceKind::Tank,
            DeviceKind::Rcs,
            DeviceKind::Computer,
            DeviceKind::Battery,
        ] {
            if let Some(name) = device_part_name(k) {
                assert!(catalog_part(name).is_some(), "{name} not in catalog for {k:?}");
            }
        }
    }

    #[test]
    fn catalog_covers_all_categories() {
        for c in PartCategory::ORDER {
            assert!(CATALOG.iter().any(|p| p.category == c), "no parts in {:?}", c);
        }
    }
}
