//! App-side voxel skinning (WI 582/583): turn the headless mesh data from
//! `sounding_sim::voxel_mesh` into a Bevy `Mesh` (with a generated tangent basis for
//! normal mapping) and bind the asset-harness PBR material set. The reusable
//! [`VoxelSkin`] selector lets any scene choose how a craft's render mesh is built.

use bevy::asset::RenderAssetUsages;
use bevy::image::{ImageAddressMode, ImageLoaderSettings, ImageSampler, ImageSamplerDescriptor};
use bevy::mesh::{Indices, PrimitiveTopology};
use bevy::prelude::*;
use sounding_sim::panel_mesh::{panel_submeshes, panel_trim_mesh};
use sounding_sim::voxel::{Material, Voxel, VoxelCraft};
use sounding_sim::voxel_mesh::{blocky_mesh, greedy_mesh, SkinMesh};

/// How a craft's render mesh is built from its voxel lattice.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum VoxelSkin {
    /// One textured cube per occupied cell — the Stormworks-style blocky skin (WI 582).
    Blocky,
    /// Coplanar faces merged into panels — the Starbase-style hull, the primary look (WI 583).
    Hull,
}

impl VoxelSkin {
    /// Generate the engine-agnostic mesh data for this skin (headless core).
    fn mesh_data(self, craft: &VoxelCraft) -> SkinMesh {
        match self {
            VoxelSkin::Blocky => blocky_mesh(craft),
            VoxelSkin::Hull => greedy_mesh(craft),
        }
    }
}

/// Build a Bevy `Mesh` for `craft` rendered with `skin`, with a generated tangent basis
/// (required for normal mapping — the `-- materials` validation flagged this).
pub fn build_skin_mesh(craft: &VoxelCraft, skin: VoxelSkin) -> Mesh {
    mesh_from_skin_data(skin.mesh_data(craft))
}

/// Convert engine-agnostic [`SkinMesh`] data into a Bevy `Mesh` with a generated
/// tangent basis — the one conversion the hull skin, panel plates, and trim all share
/// (WI 825). The generators emit unit-square face UVs, so tangent generation is valid.
fn mesh_from_skin_data(data: SkinMesh) -> Mesh {
    let mut mesh = Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::default(),
    );
    mesh.insert_attribute(Mesh::ATTRIBUTE_POSITION, data.positions);
    mesh.insert_attribute(Mesh::ATTRIBUTE_NORMAL, data.normals);
    mesh.insert_attribute(Mesh::ATTRIBUTE_UV_0, data.uvs);
    mesh.insert_indices(Indices::U32(data.indices));
    mesh.with_generated_tangents()
        .expect("skin mesh has positions, normals, and UVs")
}

/// The asset material-set basename for a structural cell (the data-shaped cell-material →
/// material-set seam, WI 582). Each structural material now binds its own **bespoke** PBR set
/// (WI 624) — brushed aluminium, polished steel, satin titanium, carbon-fibre weave — generated by
/// the asset-harness `pbr-materials` track. Any unknown / non-structural material falls back to the
/// original shared `hull_panel` set so a cell never binds a missing asset path.
pub fn material_set_for(material: Material) -> &'static str {
    match material {
        x if x == Material::ALUMINIUM => "aluminium_panel",
        x if x == Material::STEEL => "steel_plate",
        x if x == Material::TITANIUM => "titanium_panel",
        x if x == Material::COMPOSITE => "carbon_weave",
        _ => "hull_panel",
    }
}

/// Per-material surface appearance (WI 614): the **single source** for how a structural material
/// looks where a flat colour is needed — the editor gizmo voxel colour and the Build palette swatch,
/// so the palette and the built craft agree. Since WI 624 each material has its own bespoke PBR set
/// (`material_set_for`) carrying the real albedo + metallic/roughness; this `tint` is the
/// representative swatch colour, kept distinct so the palette stays legible, and it lightly biases
/// the skin's `base_color` (relaxed toward neutral so the real albedo leads — see `pbr_material`).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MaterialVisual {
    pub tint: Color,
}

/// The representative swatch colour for a structural `material` (WI 614/624). Each approximates its
/// bespoke albedo's dominant hue so the flat palette/gizmo read matches the textured surface: light
/// silvery aluminium, blue-grey steel, warm grey-gold titanium, dark charcoal carbon composite.
pub fn material_visual(material: Material) -> MaterialVisual {
    let tint = match material {
        x if x == Material::ALUMINIUM => Color::srgb(0.78, 0.80, 0.84),
        x if x == Material::STEEL => Color::srgb(0.52, 0.55, 0.60),
        x if x == Material::TITANIUM => Color::srgb(0.74, 0.68, 0.58),
        x if x == Material::COMPOSITE => Color::srgb(0.20, 0.20, 0.24),
        x if x == Material::GLASS => Color::srgb(0.62, 0.80, 0.88),
        _ => Color::srgb(0.55, 0.35, 0.55),
    };
    MaterialVisual { tint }
}

/// The distinct materials present in `craft`, in first-seen order (WI 614).
pub fn materials_present(craft: &VoxelCraft) -> Vec<Material> {
    let mut out: Vec<Material> = Vec::new();
    for v in &craft.voxels {
        if !out.contains(&v.material) {
            out.push(v.material);
        }
    }
    out
}

/// Split `craft` into one render sub-mesh per distinct material present (WI 614), so each can be bound
/// to its own [`material_visual`] appearance. Returns `(material, mesh)` pairs; empty when the craft
/// has no voxels. The union of the sub-meshes' voxels is exactly the craft's voxels.
pub fn skin_submeshes(craft: &VoxelCraft, skin: VoxelSkin) -> Vec<(Material, Mesh)> {
    materials_present(craft)
        .into_iter()
        .map(|m| {
            let mut sub = VoxelCraft::new(craft.cell_size);
            sub.voxels = craft
                .voxels
                .iter()
                .filter(|v| v.material == m)
                .cloned()
                .collect::<Vec<Voxel>>();
            (m, build_skin_mesh(&sub, skin))
        })
        .collect()
}

/// Load a texture with a **repeat-wrapped**, linear-filtered sampler so tiled UVs (UVs that
/// exceed `1.0`) repeat the texture instead of clamping/smearing the edge texel (WI 587).
/// `srgb` true for colour (albedo), false for non-colour data (normal / metallic-roughness
/// / occlusion). Shared by the craft skins and the textured ground (WI 588).
pub fn load_repeat(asset_server: &AssetServer, path: String, srgb: bool) -> Handle<Image> {
    asset_server.load_with_settings(path, move |s: &mut ImageLoaderSettings| {
        s.is_srgb = srgb;
        let mut desc = ImageSamplerDescriptor::linear();
        desc.address_mode_u = ImageAddressMode::Repeat;
        desc.address_mode_v = ImageAddressMode::Repeat;
        s.sampler = ImageSampler::Descriptor(desc);
    })
}

/// How far the skin's `base_color` is relaxed toward white over the bespoke albedo (WI 624): the
/// real per-material albedo carries the colour, so the tint is only a faint bias (avoids
/// double-saturating a coloured albedo). `0.0` = full tint, `1.0` = pure white / albedo-only.
const SKIN_TINT_RELAX: f32 = 0.7;

/// Relax a swatch `tint` toward white by [`SKIN_TINT_RELAX`] for use as a skin `base_color` multiplier
/// over a bespoke albedo (WI 624).
fn relaxed_base_color(tint: Color) -> Color {
    let c = tint.to_srgba();
    let lerp = |v: f32| v + (1.0 - v) * SKIN_TINT_RELAX;
    Color::srgb(lerp(c.red), lerp(c.green), lerp(c.blue))
}

/// Build the `StandardMaterial` for a structural `material` (WI 614/624): the material's **bespoke**
/// PBR set ([`material_set_for`]) — albedo sRGB; normal / metallic-roughness / occlusion linear —
/// repeat-wrapped so the greedy hull's tiled UVs repeat per cell. The real albedo carries the colour
/// and the metallic-roughness map carries the per-material metal/roughness, so the `base_color` is
/// only a faint relaxed tint and the metallic/roughness factors are texture-driven (1.0).
pub fn pbr_material(
    material: Material,
    asset_server: &AssetServer,
    materials: &mut Assets<StandardMaterial>,
) -> Handle<StandardMaterial> {
    let visual = material_visual(material);
    // The relax-toward-white exists to keep the tint from double-saturating a bespoke
    // albedo texture; glass is texture-less (WI 821), so its tint leads un-relaxed.
    let base = if material == Material::GLASS {
        visual.tint
    } else {
        relaxed_base_color(visual.tint)
    };
    pbr_material_with(material, base, asset_server, materials)
}

/// Like [`pbr_material`] but with the `base_color` replaced by `tint` (multiplied over the albedo
/// texture) — used to mark **panels** with a distinct cast (WI 727) so panel-vs-solid reads at a glance,
/// while keeping the material's albedo / normal / metallic-roughness detail.
pub fn pbr_material_tinted(
    material: Material,
    tint: Color,
    asset_server: &AssetServer,
    materials: &mut Assets<StandardMaterial>,
) -> Handle<StandardMaterial> {
    pbr_material_with(material, tint, asset_server, materials)
}

/// Glass translucency: the alpha the glass `base_color` carries. Low enough to read
/// through, high enough that the pane is visibly *there*.
const GLASS_ALPHA: f32 = 0.35;

/// The **texture-less translucent** `StandardMaterial` for glass (WI 821): the caller's
/// base colour at [`GLASS_ALPHA`], alpha-blended, smooth and non-metallic, **no texture
/// maps** — real glass is untextured, so this is the correct binding, not a fallback.
/// Pure (no `AssetServer`), so the one genuinely new render behavior is unit-testable.
pub fn glass_material(base_color: Color) -> StandardMaterial {
    StandardMaterial {
        base_color: base_color.with_alpha(GLASS_ALPHA),
        alpha_mode: AlphaMode::Blend,
        perceptual_roughness: 0.08,
        metallic: 0.0,
        ..default()
    }
}

/// Shared body of [`pbr_material`] / [`pbr_material_tinted`]: the material's bespoke PBR set with a
/// caller-chosen `base_color` multiplier. Glass short-circuits to [`glass_material`] —
/// translucent and texture-less (a panel tint's hue still applies; the alpha discipline holds).
fn pbr_material_with(
    material: Material,
    base_color: Color,
    asset_server: &AssetServer,
    materials: &mut Assets<StandardMaterial>,
) -> Handle<StandardMaterial> {
    if material == Material::GLASS {
        return materials.add(glass_material(base_color));
    }
    let set = material_set_for(material);
    materials.add(StandardMaterial {
        base_color,
        base_color_texture: Some(load_repeat(
            asset_server,
            format!("materials/{set}_albedo.png"),
            true,
        )),
        normal_map_texture: Some(load_repeat(
            asset_server,
            format!("materials/{set}_normal.png"),
            false,
        )),
        metallic_roughness_texture: Some(load_repeat(
            asset_server,
            format!("materials/{set}_metallic_roughness.png"),
            false,
        )),
        occlusion_texture: Some(load_repeat(
            asset_server,
            format!("materials/{set}_occlusion.png"),
            false,
        )),
        perceptual_roughness: 1.0,
        metallic: 1.0,
        ..default()
    })
}

/// A steel-blue cast for **panel** plates (WI 727 → 825): multiplied over the material's
/// albedo so panels read as panels at a glance, distinct from solid cubes which keep
/// their neutral material colour. Moved here from the harbor so every solid-render
/// scene shares one panel appearance.
pub const PANEL_TINT: Color = Color::srgb(0.42, 0.62, 1.0);

/// The frame/trim appearance (WI 825): a flat dark graphite — texture-less, so it
/// reads as a colour break against any plate or hull material. Pure (no
/// `AssetServer`), like [`glass_material`], so the binding is unit-testable. The
/// colour is a WI 825 visual knob.
pub fn trim_material() -> StandardMaterial {
    StandardMaterial {
        base_color: Color::srgb(0.13, 0.13, 0.15),
        perceptual_roughness: 0.6,
        metallic: 0.35,
        ..default()
    }
}

/// Ready-to-spawn render pieces for a craft's **face panels** (WI 825, panels design
/// stage 2): one merged plate mesh per distinct panel material in its panel-tinted
/// binding (glass routes to the translucent binding), plus the frame/trim mesh in
/// [`trim_material`]. Each scene spawns the pairs with its own markers/transforms —
/// the one seam replacing per-scene plate inference. Empty when the craft has no
/// panels, so panel-less scenes allocate nothing.
pub fn panel_render_pieces(
    craft: &VoxelCraft,
    asset_server: &AssetServer,
    materials: &mut Assets<StandardMaterial>,
    meshes: &mut Assets<Mesh>,
) -> Vec<(Handle<Mesh>, Handle<StandardMaterial>)> {
    let mut out = Vec::new();
    for (material, data) in panel_submeshes(craft) {
        let mat = pbr_material_tinted(material, PANEL_TINT, asset_server, materials);
        out.push((meshes.add(mesh_from_skin_data(data)), mat));
    }
    let trim = panel_trim_mesh(craft);
    if trim.face_count() > 0 {
        out.push((
            meshes.add(mesh_from_skin_data(trim)),
            materials.add(trim_material()),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const STRUCTURAL: [Material; 4] = [
        Material::ALUMINIUM,
        Material::STEEL,
        Material::TITANIUM,
        Material::COMPOSITE,
    ];

    #[test]
    fn four_materials_have_distinct_bespoke_sets() {
        // Each structural material binds its own set name (WI 624) — no two share, and none falls
        // back to the shared default.
        let sets: Vec<&str> = STRUCTURAL.iter().map(|m| material_set_for(*m)).collect();
        for (i, a) in sets.iter().enumerate() {
            assert_ne!(
                *a, "hull_panel",
                "a structural material fell back to the shared set"
            );
            for b in sets.iter().skip(i + 1) {
                assert_ne!(a, b, "two structural materials share a set name");
            }
        }
    }

    #[test]
    fn every_structural_set_has_its_four_maps() {
        // The bound bespoke assets must exist on disk (WI 624) — never bind a missing path.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/materials");
        for m in STRUCTURAL {
            let set = material_set_for(m);
            for map in ["albedo", "normal", "metallic_roughness", "occlusion"] {
                let p = root.join(format!("{set}_{map}.png"));
                assert!(p.exists(), "missing material asset: {}", p.display());
            }
        }
    }

    #[test]
    fn four_materials_have_distinct_tints() {
        // Guard against a copy-paste collision: no two structural materials share a tint (WI 614).
        for (i, a) in STRUCTURAL.iter().enumerate() {
            for b in STRUCTURAL.iter().skip(i + 1) {
                assert_ne!(
                    material_visual(*a).tint,
                    material_visual(*b).tint,
                    "two structural materials share a tint"
                );
            }
        }
    }

    #[test]
    fn glass_tint_is_distinct_from_the_structural_tints() {
        // WI 821: the glass swatch must not collide with any structural material's.
        for m in STRUCTURAL {
            assert_ne!(
                material_visual(Material::GLASS).tint,
                material_visual(m).tint,
                "glass shares a tint with a structural material"
            );
        }
    }

    #[test]
    fn glass_material_is_translucent_smooth_and_untextured() {
        // WI 821: the one genuinely new render behavior, unit-tested without an
        // AssetServer (glass_material is pure by design).
        let mat = glass_material(material_visual(Material::GLASS).tint);
        assert_eq!(mat.alpha_mode, AlphaMode::Blend, "alpha-blended");
        assert!(
            mat.base_color.alpha() < 1.0 && mat.base_color.alpha() > 0.0,
            "translucent, not invisible: alpha = {}",
            mat.base_color.alpha()
        );
        assert!(mat.perceptual_roughness < 0.2, "smooth");
        assert_eq!(mat.metallic, 0.0, "dielectric");
        assert!(
            mat.base_color_texture.is_none() && mat.normal_map_texture.is_none(),
            "texture-less by design — never binds a missing asset path"
        );
    }

    #[test]
    fn split_partitions_voxels_by_material() {
        // One entry per distinct material present, and the per-material counts sum to the whole
        // (no voxel dropped or duplicated) (WI 614).
        let mut craft = VoxelCraft::new(1.0);
        craft.voxels.push(Voxel {
            cell: IVec3::new(0, 0, 0),
            material: Material::ALUMINIUM,
        });
        craft.voxels.push(Voxel {
            cell: IVec3::new(1, 0, 0),
            material: Material::STEEL,
        });
        craft.voxels.push(Voxel {
            cell: IVec3::new(2, 0, 0),
            material: Material::ALUMINIUM,
        });

        let present = materials_present(&craft);
        assert_eq!(present.len(), 2, "two distinct materials present");

        let total: usize = present
            .iter()
            .map(|m| craft.voxels.iter().filter(|v| v.material == *m).count())
            .sum();
        assert_eq!(
            total,
            craft.voxels.len(),
            "partition covers every voxel once"
        );
    }

    #[test]
    fn empty_craft_has_no_submeshes() {
        let craft = VoxelCraft::new(1.0);
        assert!(skin_submeshes(&craft, VoxelSkin::Hull).is_empty());
    }

    #[test]
    fn trim_material_is_a_dark_neutral_distinct_from_every_tint() {
        // WI 825: the frame/trim colour break must not collide with any material's
        // swatch (the same distinctness discipline as the WI 614 tint tests), and it
        // must be texture-less (never binds an asset path).
        let trim = trim_material();
        let c = trim.base_color.to_srgba();
        assert!(c.red < 0.3 && c.green < 0.3 && c.blue < 0.3, "dark: {c:?}");
        for m in STRUCTURAL
            .iter()
            .copied()
            .chain(std::iter::once(Material::GLASS))
        {
            assert_ne!(trim.base_color, material_visual(m).tint);
        }
        assert_ne!(trim.base_color, PANEL_TINT, "distinct from the panel cast");
        assert!(trim.base_color_texture.is_none(), "texture-less");
    }

    #[test]
    fn skin_data_conversion_generates_tangents_for_plates_and_trim() {
        // WI 825 (plan-review note): the shared conversion path must accept the
        // panel generators' output — valid UVs ⇒ tangent generation succeeds.
        let mut craft = VoxelCraft::new(0.5);
        craft.set_face_panel(IVec3::ZERO, IVec3::X, Some(Material::STEEL));
        craft.set_face_panel(IVec3::new(0, 1, 0), IVec3::X, Some(Material::GLASS));
        for (_, data) in panel_submeshes(&craft) {
            let mesh = mesh_from_skin_data(data);
            assert!(mesh.attribute(Mesh::ATTRIBUTE_TANGENT).is_some());
        }
        let trim = mesh_from_skin_data(panel_trim_mesh(&craft));
        assert!(trim.attribute(Mesh::ATTRIBUTE_TANGENT).is_some());
    }
}
